### ISSUE TITLE
Revision numbering may be incorrect 

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/StreamRadio#19]
Current revision on HaikuDepot is 0.0.3-14. When building from jsteinaker master, the “About” box shows revision 0.0.5-1. It should probably be 0.0.4-1.

**Comment by jsteinaker** [comment]
Yeah, that's because I think we never bumped the version number on the HaikuArchives repo last year, but apparently I did on my personal repo, after a few changes that weren't merged. So when I started with StreamRadio again a couple of days ago, I've already had "version 0.0.4" from my repo and I've just bumped everything to 0.0.5 to avoid myself confusion. It's just a minor version number, it shouldn't be important, isn't it?

**Comment by humdingerb** [comment]
Nah, not important, but I still moved it back to 0.0.4 in 25bef64
